### ISSUE TITLE
The choice of license is a problem for our use-case

### ISSUE THREAD

**Issue by ArtemGovorov** [acornjs/acorn-import-meta#1]
As per discussion at https://github.com/acornjs/acorn-import-meta/commit/dd69f0f7a25942ec471b165e7e67b285535bc528#commitcomment-27494241

**Comment by adrianheine** [comment]
Would the [Apache License](https://en.wikipedia.org/wiki/Apache_License) be okay for you?

**Comment by ArtemGovorov** [comment]
Yes, thanks.

**Comment by adrianheine** [comment]
Fixed in ffbf3f30fa962bc34cbc491fc24409030eae2522 and released as 0.2.1.
